Repository gorilla-devs/GDLauncher, pull requests merged in 2023-01, with the labels that each got.

#1446 Move nsfw to dependencies, remove napi & murmur2 binaries.
  .github/workflows/nodejs.yml
  .gitignore
  package-lock.json
  package.json
  public/electron.js
  public/native/darwin/murmur2.node
  public/native/darwin/murmur2_aarch64.node
  public/native/darwin/napi.node
  public/native/darwin/nsfw.node
  public/native/darwin/nsfw_aarch64.node
  public/native/linux/murmur2.node
  public/native/linux/napi.node
  public/native/linux/nsfw.node
  public/native/murmur2.js
  public/native/napi.js
  public/native/win32/murmur2.node
  public/native/win32/napi.node
  public/native/win32/nsfw.node
  public/nsfw.js
  scripts/electronWebpackConfig.js
  scripts/moveNapi.js
  scripts/moveNsfw.js
Labels: Type: Enhancement, Status: Ready for Review

#1443 Updated base URL for fetching news images
  src/common/reducers/actions.js
Labels: Status: Ready for Review

#1451 Allow for Local ARM64 Linux Building
  .env
  package.json
  public/electron.js
  scripts/createDeploy.js
  src/app/desktop/utils/index.js
  src/common/modals/JavaSetup.js
  src/common/utils/selectors.js
Labels: Priority: High, Status: Completed

#1518 Fix windows nsfw rebase
  package-lock.json
  package.json
Labels: Priority: Critical, Status: Ready for Review

#1512 More graceful handling of blocked Curseforge browser downloads
  public/electron.js
  src/common/modals/OptedOutModsList.js
Labels: Status: Ready for Review
